### PR TITLE
bumping to lts-15.2 and ghc 8.8.2

### PR DESCRIPTION
**Pull request by MaciekFlis**
I've tested it for few simple scenarios and it seems to work.
Also, could we re-add GPipe to stackage?

### CODE REVIEW

**Comment by tobbebex** [comment]
Sorry for not tending to this until now. Guess its not latest LTS anymore, but hopefully worth something.

**Comment by MaciekFlis** [comment]
no worries, I figure we all find ourselves spending more time in our homes recently, don't we?

I assumed you will want to bump minor version before merging it? or do you do that only when adding to hackage?

**Comment by tobbebex** [comment]
Indeed! Will update to latest and upload to hackage later tonight.


9 apr. 2020 kl. 22:29 skrev MaciekFlis <notifications@github.com>:

﻿

no worries, I figure we all find ourselves spending more time in our homes recently, don't we?

I assumed you will want to bump minor version before merging it? or do you do that only when adding to hackage?

**Comment by tobbebex** [comment]
[Done!](https://hackage.haskell.org/package/GPipe-2.2.5)

**Pull request merged**
